@extends('layouts.app')
@section('title','Administración')
@section('content')
<div class="page-head"><div><span class="eyebrow">Configuración de planta</span><h1>Administración</h1><p>Gestiona zonas, departamentos, cuadrillas, dispositivos y accesos.</p></div><a class="button" href="{{ route('admin.qr.index') }}">Ver códigos QR</a></div>

<nav class="admin-tabs"><a href="#ubicaciones">Zonas y salas</a><a href="#dispositivos">Dispositivos</a><a href="#personal">Técnicos</a><a href="#equipos">Equipos de trabajo</a><a href="#departamentos">Departamentos</a></nav>

<section id="ubicaciones" class="admin-section"><div class="section-title"><div><span class="eyebrow">Planta física</span><h2>Zonas, salas y contenedores</h2></div><span class="count">{{ $locations->count() }}</span></div>
<details class="create-panel" open><summary>+ Crear ubicación</summary><form method="post" action="{{ route('admin.locations.store') }}" class="form-grid">@csrf <label>Nombre<input name="name" required></label><label>Código<input name="code" required></label><label>Tipo<select name="type" required>@foreach(\App\Models\Location::TYPES as $v=>$l)<option value="{{ $v }}">{{ $l }}</option>@endforeach</select></label><label>Zona<input name="zone"></label><label class="wide">Descripción<textarea name="description" rows="2"></textarea></label><button class="button primary" type="submit">Crear ubicación</button></form></details>
<div class="entity-list">@foreach($locations as $location)<details class="entity"><summary><span><strong>{{ $location->name }}</strong><small>{{ $location->code }} · {{ $location->type_label }} · {{ $location->assets_count }} dispositivos</small></span><span>{{ $location->active?'Activa':'Inactiva' }}</span></summary><form method="post" action="{{ route('admin.locations.update',$location) }}" class="form-grid">@csrf @method('PUT')<label>Nombre<input name="name" value="{{ $location->name }}" required></label><label>Código<input name="code" value="{{ $location->code }}" required></label><label>Tipo<select name="type">@foreach(\App\Models\Location::TYPES as $v=>$l)<option value="{{ $v }}" @selected($location->type===$v)>{{ $l }}</option>@endforeach</select></label><label>Zona<input name="zone" value="{{ $location->zone }}"></label><label class="wide">Descripción<textarea name="description">{{ $location->description }}</textarea></label><label class="check"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($location->active)> Activa</label><button class="button primary">Guardar</button></form><form method="post" action="{{ route('admin.locations.destroy',$location) }}" onsubmit="return confirm('¿Eliminar esta ubicación?')">@csrf @method('DELETE')<button class="danger-link">Eliminar</button></form></details>@endforeach</div></section>

<section id="dispositivos" class="admin-section"><div class="section-title"><div><span class="eyebrow">Activos técnicos</span><h2>Dispositivos y componentes</h2></div><span class="count">{{ $assets->count() }}</span></div>
<details class="create-panel"><summary>+ Agregar dispositivo</summary><form method="post" action="{{ route('admin.assets.store') }}" class="form-grid">@csrf @include('admin.plant.partials.asset-fields',['asset'=>null])<button class="button primary">Agregar dispositivo</button></form></details>
<div class="entity-list">@foreach($assets as $asset)<details class="entity"><summary><span><strong>{{ $asset->name }}</strong><small>{{ $asset->code }} · {{ $asset->location->name }} · {{ $asset->status_label }}</small></span><a href="{{ route('operator.asset',$asset) }}">Abrir ficha</a></summary><form method="post" action="{{ route('admin.assets.update',$asset) }}" class="form-grid">@csrf @method('PUT') @include('admin.plant.partials.asset-fields',['asset'=>$asset])<button class="button primary">Guardar</button></form><form method="post" action="{{ route('admin.assets.destroy',$asset) }}" onsubmit="return confirm('¿Eliminar este dispositivo?')">@csrf @method('DELETE')<button class="danger-link">Eliminar</button></form></details>@endforeach</div></section>

<section id="personal" class="admin-section"><div class="section-title"><div><span class="eyebrow">Accesos</span><h2>Técnicos y supervisores</h2></div><span class="count">{{ $users->count() }}</span></div>
<details class="create-panel"><summary>+ Crear cuenta</summary><form method="post" action="{{ route('admin.users.store') }}" class="form-grid">@csrf <label>Nombre<input name="name" required></label><label>Correo<input type="email" name="email" required></label><label>Contraseña temporal<input type="password" name="password" minlength="10" required></label><label>Rol<select name="role"><option value="technician">Técnico / operario</option><option value="supervisor">Supervisor</option></select></label><fieldset class="wide"><legend>Equipos de trabajo</legend>@foreach($teams as $team)<label class="check"><input type="checkbox" name="team_ids[]" value="{{ $team->id }}"> {{ $team->name }}</label>@endforeach</fieldset><button class="button primary">Crear cuenta</button></form></details>
<div class="entity-list">@foreach($users as $user)<details class="entity"><summary><span><strong>{{ $user->name }}</strong><small>{{ $user->email }} · {{ $user->role==='supervisor'?'Supervisor':'Técnico' }}</small></span><span>{{ $user->active?'Activo':'Inactivo' }}</span></summary><form method="post" action="{{ route('admin.users.update',$user) }}" class="form-grid">@csrf @method('PUT')<label>Nombre<input name="name" value="{{ $user->name }}" required></label><label>Correo<input type="email" name="email" value="{{ $user->email }}" required></label><label>Nueva contraseña<input type="password" name="password" minlength="10" placeholder="Dejar vacía para conservar"></label><label>Rol<select name="role"><option value="technician" @selected($user->role==='technician')>Técnico / operario</option><option value="supervisor" @selected($user->role==='supervisor')>Supervisor</option></select></label><fieldset class="wide"><legend>Equipos de trabajo</legend>@foreach($teams as $team)<label class="check"><input type="checkbox" name="team_ids[]" value="{{ $team->id }}" @checked($user->workTeams->contains($team))> {{ $team->name }}</label>@endforeach</fieldset><label class="check"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($user->active)> Cuenta activa</label><button class="button primary">Guardar</button></form>@if(!auth()->user()->is($user))<form method="post" action="{{ route('admin.users.destroy',$user) }}" onsubmit="return confirm('¿Eliminar esta cuenta?')">@csrf @method('DELETE')<button class="danger-link">Eliminar</button></form>@endif</details>@endforeach</div></section>

<section id="equipos" class="admin-section"><div class="section-title"><div><span class="eyebrow">Organización</span><h2>Equipos de trabajo</h2></div><span class="count">{{ $teams->count() }}</span></div><details class="create-panel"><summary>+ Crear equipo</summary><form method="post" action="{{ route('admin.teams.store') }}" class="form-grid">@csrf @include('admin.plant.partials.team-fields',['team'=>null])<button class="button primary">Crear equipo</button></form></details><div class="entity-list">@foreach($teams as $team)<details class="entity"><summary><span><strong>{{ $team->name }}</strong><small>{{ $team->department->name }} · {{ $team->users_count }} personas</small></span></summary><form method="post" action="{{ route('admin.teams.update',$team) }}" class="form-grid">@csrf @method('PUT') @include('admin.plant.partials.team-fields',['team'=>$team])<button class="button primary">Guardar</button></form><form method="post" action="{{ route('admin.teams.destroy',$team) }}" onsubmit="return confirm('¿Eliminar este equipo?')">@csrf @method('DELETE')<button class="danger-link">Eliminar</button></form></details>@endforeach</div></section>

<section id="departamentos" class="admin-section"><div class="section-title"><div><span class="eyebrow">Organización</span><h2>Departamentos</h2></div><span class="count">{{ $departments->count() }}</span></div><details class="create-panel"><summary>+ Crear departamento</summary><form method="post" action="{{ route('admin.departments.store') }}" class="form-grid">@csrf @include('admin.plant.partials.department-fields',['department'=>null])<button class="button primary">Crear departamento</button></form></details><div class="entity-list">@foreach($departments as $department)<details class="entity"><summary><span><strong>{{ $department->name }}</strong><small>{{ $department->code }} · {{ $department->teams_count }} equipos</small></span></summary><form method="post" action="{{ route('admin.departments.update',$department) }}" class="form-grid">@csrf @method('PUT') @include('admin.plant.partials.department-fields',['department'=>$department])<button class="button primary">Guardar</button></form><form method="post" action="{{ route('admin.departments.destroy',$department) }}" onsubmit="return confirm('¿Eliminar este departamento?')">@csrf @method('DELETE')<button class="danger-link">Eliminar</button></form></details>@endforeach</div></section>
@endsection
