<div class="form-grid">
 <label class="span-2">Título del trabajo<input name="title" value="{{ old('title',$workLog->title??'') }}" required placeholder="Ej.: Limpieza de filtros y verificación de presión"></label>
 <label>Equipo responsable<select name="work_team_id" required><option value="">Seleccionar</option>@foreach($teams as $team)<option value="{{ $team->id }}" @selected(old('work_team_id',$workLog->work_team_id??null)==$team->id)>{{ $team->department->name }} · {{ $team->name }}</option>@endforeach</select></label>
 <label>Ubicación<select name="location_id" id="location" required><option value="">Seleccionar</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('location_id',$workLog->location_id??request('location'))==$location->id)>{{ $location->code }} · {{ $location->name }}</option>@endforeach</select></label>
 <label>Activo técnico (opcional)<select name="asset_id" id="asset"><option value="">Trabajo general en la ubicación</option>@foreach($locations as $location)<optgroup label="{{ $location->code }} · {{ $location->name }}">@foreach($location->assets as $asset)<option value="{{ $asset->id }}" data-location="{{ $location->id }}" @selected(old('asset_id',$workLog->asset_id??null)==$asset->id)>{{ $asset->code }} · {{ $asset->name }}</option>@endforeach</optgroup>@endforeach</select></label>
 <label>Tipo de trabajo<select name="work_type" required>@foreach($types as $key=>$label)<option value="{{ $key }}" @selected(old('work_type',$workLog->work_type??'inspection')===$key)>{{ $label }}</option>@endforeach</select></label>
 <label>Prioridad<select name="priority" required>@foreach($priorities as $key=>$label)<option value="{{ $key }}" @selected(old('priority',$workLog->priority??'normal')===$key)>{{ $label }}</option>@endforeach</select></label>
 <label>Estado<select name="status" required>@foreach($statuses as $key=>$label)<option value="{{ $key }}" @selected(old('status',$workLog->status??'completed')===$key)>{{ $label }}</option>@endforeach</select></label>
 <label>Inicio<input type="datetime-local" name="started_at" value="{{ old('started_at',isset($workLog)?$workLog->started_at?->format('Y-m-d\TH:i'):now()->format('Y-m-d\TH:i')) }}" required></label>
 <label>Finalización<input type="datetime-local" name="finished_at" value="{{ old('finished_at',isset($workLog)?$workLog->finished_at?->format('Y-m-d\TH:i'):'') }}"></label>
 <label>Próxima acción<input type="datetime-local" name="next_action_at" value="{{ old('next_action_at',isset($workLog)?$workLog->next_action_at?->format('Y-m-d\TH:i'):'') }}"></label>
 <label class="span-2">Trabajo realizado<textarea name="description" rows="5" required placeholder="Describe las tareas ejecutadas, mediciones y procedimientos…">{{ old('description',$workLog->description??'') }}</textarea></label>
 <label>Resultado<textarea name="result" rows="4" placeholder="Estado final y comprobaciones">{{ old('result',$workLog->result??'') }}</textarea></label>
 <label>Observaciones<textarea name="observations" rows="4" placeholder="Desvíos, repuestos, riesgos o recomendaciones">{{ old('observations',$workLog->observations??'') }}</textarea></label>
</div><div class="form-actions"><a href="{{ isset($workLog)?route('logbook.show',$workLog):route('logbook.index') }}">Cancelar</a><button class="btn">Guardar en bitácora</button></div>
